# SpringBoot内嵌web容器配置
server:
  # SpringBoot内嵌web容器http端口号
  port: 2333
  # SpringBoot内嵌tomcat配置
  tomcat:
    # 请求编码
    uri-encoding: UTF-8
    # 队列长度
    accept-count: 200
    # 最大连接数
    max-connections: 20000
    # 连接建立超时时间
    connection-timeout: 10000
    # 最小,最大线程数
    threads:
      min-spare: 10
      max: 1000
  # 编码配置（编码过滤器）
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      enabled: true

# Spring配置
spring:
  profiles:
    active: dev
  # thymeleaf配置
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

# mybatis plus配置
mybatis-plus:
  mapper-locations: classpath:org/cny/yurayura/dao/**/*.xml

# mybatis pagehelper配置
pagehelper:
  helper-dialect: mysql
