export default {
  // 系统管理员登入页面图片验证码获取
  SYS_MANAGER_GETVERIFYCODE: '/api/sys/manager/getVerifyCode',
  // 系统管理员登入
  SYS_MANAGER_LOGIN: '/api/sys/manager/login',
  // 系统管理员注销
  SYS_MANAGER_LOGOUT: '/api/sys/manager/logout',
  // 获取当前登入管理员信息
  SYS_MANAGER_GETCURRENTMANAGERMSG: '/api/sys/manager/getCurrentManagerMsg',
  // 分页查询系统管理员
  SYS_MANAGER_GETPAGE: '/api/sys/manager/getPage',
  // 添加系统管理员
  SYS_MANAGER_INSERT: '/api/sys/manager/insert',
  // 修改系统管理员
  SYS_MANAGER_UPDATE: '/api/sys/manager/update',
  // 判断系统管理员认证状态
  SYS_MANAGER_JUDGEAUTHEN: '/api/sys/manager/judgeAuthen',
  // 查询系统侧边菜单
  SYS_MENU_GETSYSSIDEMENU: '/api/sys/menu/getSysSideMenu',
  // 查询系统菜单树形列表
  SYS_MENU_GETTREELIST: '/api/sys/menu/getTreeList',
  // 添加系统菜单
  SYS_MENU_INSERT: '/api/sys/menu/insert',
  // 修改系统菜单
  SYS_MENU_UPDATE: '/api/sys/menu/update',
  // 查询系统子菜单（根据路径）
  SYS_MENUSUB_GETBYINDEX: '/api/sys/menuSub/getByIndex',
  // 查询所有系统子菜单
  SYS_MENUSUB_GETALL: '/api/sys/menuSub/getAll',
  // 添加系统子菜单
  SYS_MENUSUB_INSERT: '/api/sys/menuSub/insert',
  // 修改系统子菜单
  SYS_MENUSUB_UPDATE: '/api/sys/menuSub/update',
  // 分页查询系统数据字典
  SYS_DICT_GETPAGE: '/api/sys/dict/getPage',
  // 添加系统数据字典
  SYS_DICT_INSERT: '/api/sys/dict/insert',
  // 修改系统数据字典
  SYS_DICT_UPDATE: '/api/sys/dict/update',
  // 查询系统数据字典（根据字典编码）
  SYS_DICT_GETBYDICTCODE: '/api/sys/dict/getByDictCode',
  // 查询权限授权树
  SYS_PERMISSION_GETPERMISSIONAUTHORTREE: '/api/sys/permission/getPermissionAuthorTree',
  // 分页查询系统权限
  SYS_PERMISSION_GETPAGE: '/api/sys/permission/getPage',
  // 添加系统权限
  SYS_PERMISSION_INSERT: '/api/sys/permission/insert',
  // 修改系统权限
  SYS_PERMISSION_UPDATE: '/api/sys/permission/update',
  // 分页查询番剧
  COMIC_GETPAGE: '/api/comic/getPage',
  // 添加番剧
  COMIC_INSERT: '/api/comic/insert',
  // 修改番剧
  COMIC_UPDATE: '/api/comic/update',
  // 批量删除番剧（根据id组）
  COMIC_DELETEBATCHBYIDS: '/api/comic/deleteBatchByIds',
  // 分页查询用户
  USER_GETPAGE: '/api/user/getPage',
  // 修改状态（根据id）
  USER_UPDATESTATUS: '/api/user/updateStatus',
  // 重置为默认头像（根据id）
  USER_UPDATEAVATARDEFAULT: '/api/user/updateAvatarDefault'
}