# Spring配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yurayura_new?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 180000
      minimum-idle: 15
      maximum-pool-size: 100
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: ELiaNaCcHikariCP
  # 发送邮箱配置
  mail:
    host: smtp.126.com
    username: elianacc@126.com
    password: cny123456
    default-encoding: UTF-8
  # 文件上传配置
  servlet:
    multipart:
      # 上传文件位置
      location: D://yurayura-v1/upload/
      # 单个文件的最大值
      max-file-size: 10MB
      # 总上传文件的最大值
      max-request-size: 10MB
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    jedis:
      pool:
        max-active: 200
        max-wait: 100000
        max-idle: 10
        min-idle: 0
    timeout: 50000

# 自定义配置
yurayura:
  # 番剧上传默认图片
  default-upload:
    comic-image: /images/tpjxz.jpg
  # swagger是否启用
  swagger:
    enable: true
  # 接收邮箱
  receive-email: elianacc@126.com
  # 上传文件对外暴露的访问路径(虚拟路径)
  upload-file:
    virtual-path: /upload/**