# Spring配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yurayura_service?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 此属性控制从池返回的连接的默认自动提交行为，默认值：true
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 300000
      # 最小空闲连接数量，默认是10
      minimum-idle: 30
      # 连接池最大连接数，默认是10
      maximum-pool-size: 50
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间，默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: ELiaNaCcHikariCP
  # 发送邮箱配置
  mail:
    host: smtp.126.com
    username: elianacc@126.com
    password: cny123456
    default-encoding: UTF-8
  # 文件上传配置
  servlet:
    multipart:
      # 上传文件位置
      location: D://yurayura-upload-resource/upload
      # 单个文件的最大值
      max-file-size: 10MB
      # 总上传文件的最大值
      max-request-size: 10MB
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    jedis:
      pool:
        max-active: 200
        max-wait: 100000
        max-idle: 10
        min-idle: 0
    timeout: 50000

# lock4j配置
lock4j:
  acquire-timeout: 3000
  expire: 10000
  primary-executor: com.baomidou.lock.executor.RedisTemplateLockExecutor
  lock-key-prefix: lock4j

# knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: admin123

# 自定义配置
yurayura:
  # 上传默认图片
  default-upload:
    comic-image: /images/tpjxz.jpg
    user-avatar: /images/df_avatar.jpg
  # swagger是否启用
  swagger:
    enable: true
  # 接收邮箱
  receive-email: elianacc@126.com
  # 上传文件对外暴露的访问路径(虚拟路径)
  upload-file:
    virtual-path: /upload
